apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-container
        image: 953596634933.dkr.ecr.ap-south-1.amazonaws.com/kubernetes:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
